lint:
    stage: test
    image: "python:3.8"
    script:
        - pip install flake8 flake8-docstrings black[jupyter] black isort
        - isort --check .
        - black --check .
        - flake8 .


run_tests:
    stage: test
    image: "python:3.8"
    script:
        # missing dependencies for docker-container
        - apt-get update && apt-get install libgl1 -y
        - pip install .
        - pip install pytest pytest-cov
        - pytest --cov=./pyGCodeDecode/ --cov-config=pyproject.toml --cov-report term
            --cov-report xml:./pyGCodeDecode/test/coverage.xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        untracked: true
        paths:
            - test-artifacts/
        reports:
            coverage_report:
                coverage_format: cobertura
                path: ./pyGCodeDecode/test/coverage.xml
