test-lint:
    stage: test
    image: "python:latest"
    script:
        - pip install flake8 flake8-docstrings black[jupyter] black isort
        - isort --check . -v
        - black --check */ -v
        - flake8 . -v

test-lin_py38:
    stage: test
    image: "python:latest"
    script:
        # missing dependencies for docker-container
        - apt-get update && apt-get install libgl1 -y
        - pip install .[TEST]
        - pytest --cov --cov-config=pyproject.toml --cov-report term
          --cov-report xml:./pyGCodeDecode/test/coverage.xml
    coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)$/'
    artifacts:
        untracked: false
        # paths:
        #     - ./pyGCodeDecode/test/coverage.xml
        reports:
            coverage_report:
                coverage_format: cobertura
                path: ./pyGCodeDecode/test/coverage.xml

deploy-compile_paper:
    stage: deploy
    script:
        - docker run --rm --volume $PWD/paper:/data --user $(id -u):$(id -g)
          --env JOURNAL=joss openjournals/inara
    tags:
        - shell
    artifacts:
        untracked: false
        paths:
            - ./paper/*.pdf
        when: on_success
        expire_in: "30 days"
