lint:
    stage: test
    image: "python:3.8"
    script:
        - pip install flake8 flake8-docstrings black[jupyter] black isort
        - isort --check .
        - black --check .
        - flake8 .

test:
    stage: test
    image: "python:3.8"
    script:
        - py -m pip install --upgrade pip
        - pip install . -v
