# This configuration file defines the hooks to be executed at each commit
repos:
# Pre-commit itself
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
        args:
        - --maxkb=5000
    -   id: fix-encoding-pragma
# Black code style formatter
-   repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
# isort import sorting
-   repo: https://github.com/timothycrosley/isort
    rev: '5.10.1'
    hooks:
      - id: isort
        args: ["--profile", "black"]
# Flake8 for linting
-   repo: https://gitlab.com/pycqa/flake8
    rev: '3.9.2'
    hooks:
    -   id: flake8
