[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]

[tool.setuptools.package-data]
"pyGCodeDecode" = ["data/*", "examples/data/*"]

[project]
name = "pyGCodeDecode"
version = "1.4.4"
authors = [
    { name = "FAST-LB at KIT", email = "lt-github@fast.kit.edu" },
    { name = "Jonathan Knirsch", email = "jonathan.knirsch@student.kit.edu" },
    { name = "Felix Frölich", email = "felix.froelich@kit.edu" },
    { name = "Lukas Hof", email = "lukas.hof@kit.edu" },
]
description = "Generate time dependent boundary conditions from a .gcode file."
readme = "README.md"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.10"
dependencies = ["numpy", "matplotlib", "PyYAML", "pyvista"]

[project.optional-dependencies]
TEST = ["pytest-cov", "pandas"]
DEVELOPER = ["ruff", "pre-commit", "pytest-cov"]
DOCS = [
    "mkdocs",
    "pydoc-markdown",
    # Needs this custom fork to sort modules: git+https://github.com/jeknirsch/pydoc-markdown.git@sort_modules
]

[project.urls]
Code = "https://github.com/FAST-LB/pyGCodeDecode"
Issues = "https://github.com/FAST-LB/pyGCodeDecode/issues"

[project.scripts]
pygcd = "pyGCodeDecode.cli:_main"

[tool.ruff]
line-length = 160
target-version = "py310"

[tool.ruff.lint]
select = [
    "I",   # isort
    "F",   # pyflakes
    "E",   # pydocstyle errors
    "W",   # pydocstyle warnings
    "D",   # pydocstyle
    "UP",  # pyupgrade
    "RUF", # ruff
    "ANN", # function annotations
    "S",   # bandit security linter
    "NPY", # NumPy
    "A",   # builtins
    "C4",  # list comprehensions
    "ICN", # import conventions
    "PTH", # pathlib
    "PD",  # pandas-vet
    "PLE", # Pylint errors
    "B",   # bugbear
    # suggested but unused rulesets:
    # "N",   # PEP8-naming
]

[tool.ruff.lint.per-file-ignores]
"tests/**" = ["S101"] # Allow use of assert in tests

[tool.ruff.lint.pydocstyle]
convention = "pep257"

[tool.coverage.paths]
source = ["./pyGCodeDecode/"]

[tool.coverage.run]
omit = ["./tests/*", "./example/*"]

[tool.coverage.report]
# Regexes for lines to exclude from consideration
exclude_also = ["if __name__ == .__main__.:", "except", "import"]
