name: Tests

on: [push]

jobs:
    linting:
        runs-on: ubuntu-latest
        steps:
            - name: linting
              uses: actions/setup-python@v4
              with:
                python-version: "3.12"
            - uses: actions/checkout@v4
            - run: |
                pip install isort black[jupyter] flake8-docstrings
                isort --check . -v
                black --check */ -v
                flake8 . -v

    pytest:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest] # [ubuntu-latest, windows-latest, macos-latest]
                python-version: ["3.10"] # ["3.8", "3.9", "3.10", "3.11", "3.12"]
        steps:
            - name: test python ${{ matrix.python-version }} on ${{ matrix.os }}
              uses: actions/setup-python@v4
              with:
                python-version: ${{ matrix.python-version }}
            - uses: actions/checkout@v4

            - run: |
                pip install .[TEST]
                pytest --cov=. --cov-config=pyproject.toml --cov-report term \
                  --cov-report xml:./tests/coverage.xml
            - name: Upload
              uses: actions/upload-artifact@v1
              with:
                name: coverage_report
                path: ./pyGCodeDecode/test/coverage.xml
